In [10]:
'''In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

We can create a NumPy ndarray object by using the array() function.
'''
#Numpy ndarray
import numpy as np
data=[[2,6,1,3,7],[5,10,4,9,8]]
data=np.array(data)
print (data)
print(type(data))
print(data.ndim)
print(data.shape)


[[ 2  6  1  3  7]
 [ 5 10  4  9  8]]
<class 'numpy.ndarray'>
2
(2, 5)


In [9]:
#Produce an array of all 1's
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
array=np.arange(19)
print(array)
print(array[2:5])
print(array[5:8])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[2 3 4]
[5 6 7]


In [19]:
#ARRAY OPERATIONS
data=np.array([[5,6,7],[8,9,10]])
print(data+5)
print(data-3)
print(data*data)


[[10 11 12]
 [13 14 15]]
[[2 3 4]
 [5 6 7]]
[[ 25  36  49]
 [ 64  81 100]]


In [22]:
#Transposing and swaping Axis
data=np.arange(16).reshape((4,4))
print(data)
#Transpose of an array
print(" ")
print(data.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
 
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [23]:
x=np.random.randn(2,3)
print(x)

[[-0.83433285  0.70964872 -1.14558266]
 [ 0.55317526  0.26504468 -1.8175386 ]]


In [25]:
#STATISTICAL METHODS
#Random Data
data=np.random.randn(3,2)
print(data)
print(data.mean())
print(data.min())
print(data.max())

[[-0.92862522  0.34426808]
 [-0.4146192   0.56790004]
 [-0.58441572  1.17640104]]
0.026818169759928085
-0.92862521920215
1.1764010408544554


In [27]:
#MAtrix Class

x=np.random.randn(3,2)
x=np.matrix(x)

y=np.random.randn(2,2)
y=np.matrix(y)

print(x*y)

[[-0.11336526  0.76209251]
 [-0.10889836 -0.74239843]
 [-0.1934763  -1.32101804]]
